version: '3.8'
services:
  servicea:
    build: 
      context: serviceA
      dockerfile: docker/Dockerfile
    container_name: serviceA
    ports:
      - "8080:8080"
    environment:
      - SERVICEB_ENDPOINT=http://serviceb:8081/api/v1/weather
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://jaeger:4317
      - OTEL_EXPORTER_OTLP_TRACES_INSECURE=true
    restart: unless-stopped
  serviceb:
    build: 
      context: serviceB
      dockerfile: docker/Dockerfile
    container_name: serviceB
    ports:
      - "8081:8081"
    env_file:
      - serviceB/configs/.env
    environment:
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://jaeger:4317
      - OTEL_EXPORTER_OTLP_TRACES_INSECURE=true
    restart: unless-stopped 
  jaeger:
    image: jaegertracing/jaeger:2.8.0
    container_name: jaeger
    ports:
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "9411:9411"
